<h1>Création d'un nouvel évènement</h1>

<form method="post">
    <div class="form-group">
        <label for="title">Titre</label>
        <input type="text" name="title" id="title" class="form-control">
    </div>
    <div class="form-group">
        <label for="start">Debut de l'evenement</label>
        <input type="date" name="started_at" id="started_at" class="form-control" cols="30" rows="10">
    </div>
    <div class="form-group">
        <label for="description">Description</label>
        <textarea name="description" id="description" class="form-control" cols="30" rows="10"></textarea>
    </div>
    <div class="form-group">
        <label for="category">Catégories</label>
        <select name="category" id="category" class="form-control">
            <?php foreach ($categories as $category): ?>
                <option value="<?= $category['id'] ?>"><?= ucfirst($category['name']) ?></option>
            <?php endforeach ?>
        </select>
    </div>
    <div class="mt-2">
        <button class="btn btn-primary">Ajouter</button>
    </div>
</form>

