<h1>Accueil</h1>

<ul class="list-unstyled">
    <?php foreach ($events as $event): ?>
        <li>
            <article class="my-2">
                <header class="border-bottom py-2">
                    <h2><a href="#"><?= htmlspecialchars($event['title']) ?></a></h2>
                    <small><?= $event['created_at'] ?></small>
                </header>
                <?= nl2br(htmlspecialchars(substr($event['description'], 0, 300))) ?>[...] (<a href="#">voir la suite</a>)
            </article>
        </li>
        
    <?php endforeach ?>
</ul>
